<?php 
/*
 * for content filter in frontend;
 */
global $mltlngg_wp_providers;
$mltlngg_wp_providers = array( 
	'/(https?:\/\/(www\.)?youtube\.com\/(watch|playlist)[\?=\w-&;:^*#@!%()+]*)/i', 
	'/(https?:\/\/youtu\.be\/.*)/i',      
	'/(http:\/\/blip\.tv\/.*)/',
	'/(https?:\/\/(.+\.)?vimeo\.com\/.*)/i',
	'/(https?:\/\/(www\.)?dailymotion\.com\/.*)/i',
	'/(http:\/\/dai\.ly\/*)/',
	'/(https?:\/\/(www\.)?flickr\\.com\/.*)/i',
	'/(https?:\/\/flic\.kr\/.*)/i',
	'/(https?:\/\/(.+\.)?smugmug\.com\/.*)/i',
	'/(https?:\/\/(www\.)?hulu\.com\/watch\/.*)/i',
	'/(http:\/\/revision3.com\/*)/',
	'/(http:\/\/i*.photobucket.com\/albums\/.*)/',
	'/(http:\/\/gi*\.photobucket\.com\/groups\/.*)/',
	'/(https?:\/\/(www\.)?scribd\.com\/doc\/.*)/i',
	'/(https?:\/\/wordpress\.tv[\/\?=\w-]*)/i',
	'/(https?:\/\/(.+\.)?polldaddy\.com\/.*)/i',
	'/(https?:\/\/poll\.fm\/.*)/i',
	'/(https?:\/\/(www\.)?funnyordie\.com\/videos\/.*)/i',
	'/(https?:\/\/(www\.)?twitter\.com\/.+?\/status(es)?\/.*)/i',
	'/(https?:\/\/vine.co\/v\/.*)/i',
	'/(https?:\/\/(www\.)?soundcloud\.com\/.*)/i',
	'/(https?:\/\/(.+?\.)?slideshare\.net\/.*)/i',
	'/(http:\/\/instagr(\.am|am\.com)\/p\/.*)/i',
	'/(https?:\/\/(www\.)?rdio\.com\/.*)/i',
	'/(https?:\/\/rd\.io\/x\/.*)/i',
	'/(https?:\/\/(open|play)\.spotify\.com\/.*)/i',
	'/(https?:\/\/(.+\.)?imgur\.com\/.*)/i',
	'/(https?:\/\/(www\.)?meetu(\.ps|p\.com)\/.*)/i',
	'/(https?:\/\/(www\.)?issuu\.com\/.+\/docs\/.+)/i',
	'/(https?:\/\/(www\.)?collegehumor\.com\/video\/.*)/i',
	'/(https?:\/\/(www\.)?mixcloud\.com\/.*)/i',
	'/(https?:\/\/(www\.|embed\.)?ted\.com\/talks\/.*)/i',
	'/(https?:\/\/(www\.)?(animoto|video214)\.com\/play\/[\?=\w-&;:^*#@!%()+]*)/i'
);